//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punnel.CPanel
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationSite
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Domain { get; set; }
        public string ConfigId { get; set; }
        public string Notes { get; set; }
        public int Type { get; set; }
        public bool Actived { get; set; }
    }
}
