//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punnel.Core.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Email {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Email() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Punnel.Core.Entities.Resources.Email", typeof(Email).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;padding-bottom:20px;max-width:600px;margin: 0 auto;&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td&gt;
        ///                &lt;table cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///                    &lt;tbody&gt;
        ///                        &lt;tr&gt;
        ///                            &lt;td&gt;&lt;/td&gt;
        ///                            &lt;td&gt;
        ///                                {#HEADER}
        ///                            &lt;/td&gt;
        ///                            &lt;td&gt;&lt;/td&gt;
        ///                        &lt;/tr&gt;
        ///                   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CONTAINER {
            get {
                return ResourceManager.GetString("CONTAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=&quot;text-align:center&quot;&gt;
        ///    &lt;div style=&quot;font-family:Roboto-Regular,Helvetica,Arial,sans-serif;color:rgba(0,0,0,0.54);font-size:12px;line-height:20px;padding-top:10px&quot;&gt;
        ///        &lt;div&gt;Bạn nhận được thư này vì bạn là thành viên của punnel&lt;/div&gt;
        ///        &lt;div style=&quot;direction:ltr&quot;&gt;© 2018 PUNNEL.com&lt;/div&gt;
        ///    &lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string FOOTER {
            get {
                return ResourceManager.GetString("FOOTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table border=&quot;0&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; style=&quot;direction:ltr;padding-bottom:7px&quot; width=&quot;100%&quot;&gt;
        ///    &lt;tbody&gt;
        ///        &lt;tr&gt;
        ///            &lt;td align=&quot;left&quot;&gt;&lt;img height=&quot;32&quot; src=&quot;https://app.punnel.com/images/logo-full-color.png&quot; style=&quot;width:92px;height:32px&quot; width=&quot;92&quot;&gt;&lt;/td&gt;
        ///            &lt;td align=&quot;right&quot; style=&quot;font-family:Roboto-Light,Helvetica,Arial,sans-serif&quot;&gt;{#USER_FULLNAME}&lt;/td&gt;
        ///            &lt;td align=&quot;right&quot; width=&quot;35&quot;&gt;&lt;img height=&quot;28&quot; src=&quot;{#USER_AVATAR}&quot; style=&quot;width:28px;height:28px;border [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HEADER {
            get {
                return ResourceManager.GetString("HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Ch&amp;agrave;o {#FULLNAME},&lt;/p&gt;
        ///&lt;p&gt;Punnel th&amp;ocirc;ng b&amp;aacute;o thời gian sử dụng dịch vụ của bạn tr&amp;ecirc;n Punnel đến ng&amp;agrave;y {#DATE} l&amp;agrave; hết hạn.&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Bạn nhớ gia hạn dịch vụ sớm để c&amp;ocirc;ng việc kh&amp;ocirc;ng bị gian đoạn.&lt;/p&gt;
        ///&lt;p&gt;Link gia hạn:&amp;nbsp;&lt;a href=&quot;https://www.facebook.com/punnel.community&quot; target=&quot;_blank&quot; rel=&quot;noopener&quot;&gt;V&amp;agrave;o gia hạn dịch vụ&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Punnel lu&amp;ocirc;n cam kết đồng h&amp;agrave;nh ng&amp;agrave;y c&amp;agrave;ng ho&amp;agrave;n thiện dịch vụ, sản ph [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NOTIFY_EXPIRED {
            get {
                return ResourceManager.GetString("NOTIFY_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Ch&amp;agrave;o {#FULLNAME},&lt;/p&gt;
        ///&lt;p&gt;Punnel th&amp;ocirc;ng b&amp;aacute;o thời gian trải nghiệm của bạn tr&amp;ecirc;n Punnel đến ng&amp;agrave;y {#DATE} l&amp;agrave; hết hạn.&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Bạn cảm thấy c&amp;oacute; h&amp;agrave;i l&amp;ograve;ng kh&amp;ocirc;ng?&lt;/p&gt;
        ///&lt;p&gt;Nếu cần tư vấn bạn h&amp;atilde;y li&amp;ecirc;n hệ bằng c&amp;aacute;ch truy cập &lt;a href=&quot;https://punnel.com&quot; target=&quot;_blank&quot; rel=&quot;noopener&quot;&gt;&lt;strong&gt;punnel.com&lt;/strong&gt;&lt;/a&gt; v&amp;agrave; gửi tin nhắn cho m&amp;igrave;nh qua Facebook Messenger ngay b&amp;ecirc;n dưới để được giải đ&amp;aacute;p nh&amp;eac [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NOTIFY_FREEMEMBER_EXPIRED {
            get {
                return ResourceManager.GetString("NOTIFY_FREEMEMBER_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;p&gt;Dịch vụ trả lời tự động của bạn trên Punnel đang gặp vấn đề, vui lòng kiểm tra lại&lt;/p&gt;
        ///&lt;p&gt;{#CONTENT}&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;https://support.punnel.com/article/57-gia-han-ket-noi-google-sheet-gmail-tren-punnel&quot;&gt;Hướng dẫn gia hạn kết nối của Gmail, Gsheet trên Punnel&lt;/a&gt;&lt;/p&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string NOTIFY_INTEGRATIONAPP_ERROR {
            get {
                return ResourceManager.GetString("NOTIFY_INTEGRATIONAPP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Hey {#NAME}!&lt;/p&gt;
        ///&lt;p&gt;Vừa c&amp;oacute; kh&amp;aacute;ch mới đăng k&amp;iacute; tr&amp;ecirc;n Landing Page của bạn!&lt;/p&gt;
        ///&lt;p&gt;Landing Page: {#LINK}&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Th&amp;ocirc;ng tin kh&amp;aacute;ch h&amp;agrave;ng:&lt;/p&gt;
        ///&lt;p&gt;{#CUSTOMER_INFO}&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Bạn vào quản trị leads trong punnel để xem chi tiết nhé!&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;&lt;em&gt;Punnel Lead Service,&lt;/em&gt;&lt;/p&gt;.
        /// </summary>
        public static string NOTIFY_NEW_LEAD {
            get {
                return ResourceManager.GetString("NOTIFY_NEW_LEAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Ch&amp;agrave;o {#FULLNAME},&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;T&amp;agrave;i khoản Punnel của bạn đ&amp;atilde; được n&amp;acirc;ng cấp &amp;amp; gia hạn th&amp;agrave;nh c&amp;ocirc;ng!&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;Punnel gửi lại th&amp;ocirc;ng tin cho bạn x&amp;aacute;c nhận.&lt;/p&gt;
        ///&lt;p&gt;G&amp;oacute;i dịch vụ: {#SERVICE}&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Thời gian: {#MONTH} tháng&lt;/p&gt;
        ///&lt;p&gt;Ng&amp;agrave;y hết hạn: {#EXPIRED_DATE}&lt;/p&gt;
        ///&lt;p&gt;Nếu c&amp;oacute; thắc mắc cần trợ gi&amp;uacute;p h&amp;atilde;y li&amp;ecirc;n hệ bằng c&amp;aacute;ch truy cập &lt;a href=&quot;https://punnel.com&quot; target=&quot;_blank&quot; rel=&quot;noo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NOTIFY_PAYMENT_SUCCESS {
            get {
                return ResourceManager.GetString("NOTIFY_PAYMENT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Ch&amp;agrave;o,&lt;/p&gt;
        ///&lt;p&gt;&lt;strong&gt;Kh&amp;aacute;ch h&amp;agrave;ng th&amp;ocirc;ng b&amp;aacute;o chuyển khoản thanh to&amp;aacute;n dịch vụ Punnel&lt;/strong&gt;&lt;/p&gt;
        ///&lt;p&gt;Vui l&amp;ograve;ng kiểm tra th&amp;ocirc;ng tin thanh to&amp;aacute;n để gia hạn cho kh&amp;aacute;ch.&lt;/p&gt;
        ///&lt;p&gt;M&amp;atilde; đơn h&amp;agrave;ng: {#PAYMENT_CODE}&lt;/p&gt;
        ///&lt;p&gt;Kh&amp;aacute;ch h&amp;agrave;ng: {#CUSTOMER_EMAIL}&lt;/p&gt;
        ///&lt;p&gt;G&amp;oacute;i dịch vụ: {#SERVICE}&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Thời gian: {#MONTH}&lt;/p&gt;
        ///&lt;p&gt;Tổng tiền: {#TOTAL_AMOUNT}&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;.
        /// </summary>
        public static string NOTIFY_PAYMENT_TO_ADMIN {
            get {
                return ResourceManager.GetString("NOTIFY_PAYMENT_TO_ADMIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;p&gt;Để tạo lại mật khẩu mới trên Punnel.com hãy click vào link bên dưới:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;{#LINK-URL}&quot; target=&quot;_blank&quot;&gt;{#LINK}&lt;/a&gt;&lt;/p&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string RESET_PASS {
            get {
                return ResourceManager.GetString("RESET_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///&lt;p&gt;Để xác nhận email tài khoản trên Punnel.com hãy click vào link bên dưới:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;{#LINK-URL}&quot; target=&quot;_blank&quot;&gt;{#LINK}&lt;/a&gt;&lt;/p&gt;
        ///&lt;/div&gt;.
        /// </summary>
        public static string VERIFY_EMAIL {
            get {
                return ResourceManager.GetString("VERIFY_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Chào {#FULLNAME},&lt;/p&gt;
        ///&lt;p&gt;Chào mừng bạn gia nhập thành viên của cộng đồng Punnel&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Trước khi bắt đầu, hãy xem qua những thông tin dưới đây&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;https://support.punnel.com&quot; target=&quot;_blank&quot; rel=&quot;noopener&quot;&gt;Hướng dẫn sử dụng c&amp;ocirc;ng cụ tạo Landing Page&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;https://www.facebook.com/punnel.community&quot; target=&quot;_blank&quot; rel=&quot;noopener&quot;&gt;Thông tin chia sẻ, trao đổi cộng đồng Punnel &lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Chúc bạn thành công!&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WELCOME {
            get {
                return ResourceManager.GetString("WELCOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Chào {#FULLNAME},&lt;/p&gt;
        ///&lt;p&gt;Chào mừng bạn gia nhập thành viên của cộng đồng Punnel&lt;/p&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;div&gt;
        ///&lt;p&gt;Để xác nhận email tài khoản trên Punnel.com hãy click vào link bên dưới:&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;{#LINK-URL}&quot; target=&quot;_blank&quot;&gt;{#LINK}&lt;/a&gt;&lt;/p&gt;
        ///&lt;/div&gt;
        ///&lt;p&gt;&amp;nbsp;&lt;/p&gt;
        ///&lt;p&gt;Trước khi bắt đầu, hãy xem qua những thông tin dưới đây&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;https://support.punnel.com&quot; target=&quot;_blank&quot; rel=&quot;noopener&quot;&gt;Hướng dẫn sử dụng c&amp;ocirc;ng cụ tạo Landing Page&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;&lt;a href=&quot;https://www.facebook.com/punnel.co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WELCOME_WITH_VERIFY_EMAIL {
            get {
                return ResourceManager.GetString("WELCOME_WITH_VERIFY_EMAIL", resourceCulture);
            }
        }
    }
}
