//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Punnel.Core.Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Punnel.Core.Entities.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin kết nối không còn hợp lệ. Vui lòng hủy &amp; kết nối lại.
        /// </summary>
        public static string Api_Err {
            get {
                return ResourceManager.GetString("Api_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi kết nối. Api Key không hợp lệ.
        /// </summary>
        public static string ApiKey_Err {
            get {
                return ResourceManager.GetString("ApiKey_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không thể xóa thông tin này.
        /// </summary>
        public static string CanNotDelete {
            get {
                return ResourceManager.GetString("CanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên miền (domain) không hợp lệ. Vui lòng kiểm tra tên miền đã cấu hình đúng về DNS Server dns.punnel.com.
        /// </summary>
        public static string Domain_Invalid {
            get {
                return ResourceManager.GetString("Domain_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên miền (domain) này đã được sử dụng cho landing page khác không thuộc sở hữu của bạn!.
        /// </summary>
        public static string Domain_Used {
            get {
                return ResourceManager.GetString("Domain_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email này đã tồn tại.
        /// </summary>
        public static string Email_exist {
            get {
                return ResourceManager.GetString("Email_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản Gmail {0} đã hết hạn truy cập, vui lòng kết nối lại.
        /// </summary>
        public static string Gmail_Expired {
            get {
                return ResourceManager.GetString("Gmail_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản Gsheet {0} đã hết hạn truy cập, vui lòng kết nối lại.
        /// </summary>
        public static string GSheet_Expired {
            get {
                return ResourceManager.GetString("GSheet_Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chỉ cho phép upload file hình .jpg,image/*,.jpeg,.png,.gif,.svg,.ico.
        /// </summary>
        public static string Image_Err_Ext {
            get {
                return ResourceManager.GetString("Image_Err_Ext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng upload file dung lượng nhỏ hơn {0} MB.
        /// </summary>
        public static string Image_Err_MaxSize {
            get {
                return ResourceManager.GetString("Image_Err_MaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File import không hợp lệ!.
        /// </summary>
        public static string LandingPage_Export_FileNotAllowed {
            get {
                return ResourceManager.GetString("LandingPage_Export_FileNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trang LangdingPage không tồn tại trong hệ thống.
        /// </summary>
        public static string LandingPage_NotFound {
            get {
                return ResourceManager.GetString("LandingPage_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại này đã tồn tại.
        /// </summary>
        public static string Phone_exist1 {
            get {
                return ResourceManager.GetString("Phone_exist1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài khoản của bạn chỉ được xuất bản tối đa 3 landing page. Vui lòng nâng cấp để sử dụng không giới hạn!.
        /// </summary>
        public static string RequiredUpgrade_MaxPage {
            get {
                return ResourceManager.GetString("RequiredUpgrade_MaxPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã code không hợp lệ!.
        /// </summary>
        public static string ShareCode_Invalid {
            get {
                return ResourceManager.GetString("ShareCode_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có lỗi xảy ra. Vui lòng thử lại.
        /// </summary>
        public static string System_Err {
            get {
                return ResourceManager.GetString("System_Err", resourceCulture);
            }
        }
    }
}
